feat: Add tags as part of the job event metadata
sorentwo/oban pull request #334
Opened 2020-09-13 23:08 UTC by milmazz

Now the `[:oban, :job, {:start|:stop|:exception}]` telemetry events include the Job tags as part of their metadata.

2020-09-14 12:35 UTC, sorentwo requested changes
I'm surprised this didn't come up before. That may indicate how infrequently people use tags. Anyhow, the changes look great. Get that test swapped over and this is ready to go.

2020-09-14 12:35 UTC, sorentwo commented on test/oban/queue/executor_test.exs
> +    test "tags are included in the job metadata" do
This test should be included in `test/integration/telemetry_test.exs` instead. Take a look at the assertion around line 50.

2020-09-14 17:14 UTC, milmazz commented
> I'm surprised this didn't come up before. That may indicate how infrequently people use tags. Anyhow, the changes look great. Get that test swapped over and this is ready to go.

I forgot to mention the use case, the team I'm working with is collecting telemetry metrics, we're publishing the worker, node, and a few other entries as tags for those events, and we would like to be able to include the `tags` from the Oban Job too.

Regarding your request, I'll start working asap on this.

2020-09-14 17:34 UTC, milmazz commented
@sorentwo I think I addressed your comment. Please let me know what do you think.

2020-09-15 16:39 UTC, sorentwo approved these changes

2020-09-15 16:40 UTC, merged

2020-09-15 16:40 UTC, sorentwo commented
Thanks @milmazz 💛