Add Oban.cancel_all_jobs/0,1,2
sorentwo/oban pull request #527
Opened 2021-08-04 04:50 UTC by v0idpwn

As suggested in #514

2021-08-04 05:01 UTC, v0idpwn commented on lib/oban.ex
> +      query = Ecto.Query.where(Oban.Job, worker: MyApp.MyWorker)
wait, this query doesn't work, right?

2021-08-04 14:13 UTC, sorentwo requested changes
Great start, I dig the approach 👍

2021-08-04 14:13 UTC, sorentwo commented on lib/oban.ex
> +  If any the jobs is currently `executing` it will be killed and otherwise it is ignored.
```suggestion
  Any currently `executing` jobs are killed while the others are ignored.
```

2021-08-04 14:13 UTC, sorentwo commented on lib/oban.ex
> +  Only jobs with the statuses`executing`, `available`, `scheduled` or `retryable` can be cancelled.
```suggestion
  If executing jobs happen to fail before cancellation then the state is set to `cancelled`.
  However, any that complete successfully will remain `completed`.

  Only jobs with the statuses `executing`, `available`, `scheduled`, or `retryable` can be cancelled.
```

2021-08-04 14:13 UTC, sorentwo commented on lib/oban.ex
> +      query = Ecto.Query.where(Oban.Job, worker: MyApp.MyWorker)
```suggestion
      query = Ecto.Query.where(Oban.Job, worker: "MyApp.MyWorker")
```

2021-08-04 14:13 UTC, sorentwo commented on lib/oban/queue/basic_engine.ex
> +      |> select([:id])
We can avoid the extra map by selecting the id directly:

```suggestion
      |> select([j], j.id)
```

2021-08-04 14:13 UTC, sorentwo commented on lib/oban.ex
> +    {:ok, Enum.count(job_ids)}
A couple of things here:

1. `Notifier.notify/3` can take a list of messages instead, which lets it make a single database call
2. We should only emit a notification if there is at least one job id
3. `Enum.count/1` will delegate to `length/1` for a list, may as well skip the middleman

```suggestion
    case Engine.cancel_all_jobs(conf, queryable) do
      {:ok, [_ | _] = job_ids} ->
        payload = Enum.map(job_ids, &%{action: :pkill, job_id: &1})

        Notifier.notify(conf, :signal, payload)

        {:ok, length(job_ids)}

      _ ->
        {:ok, 0}
    end
```

2021-08-05 17:30 UTC, sorentwo approved these changes
Looks great! There is an `swp` file sitting around, so I'll fix it up and merge locally.

2021-08-05 17:30 UTC, sorentwo commented on lib/oban.ex
> +        payload = Enum.map(job_ids, fn id -> %{action: :pkill, job_id: id} end)
Not a fan of the captured map syntax, eh?

2021-08-05 17:45 UTC, sorentwo commented
Merged with 313a753

2021-08-05 17:45 UTC, closed without merging