Select only id in stage subquery
sorentwo/oban pull request #846
Opened 2023-02-14 14:40 UTC by alexcastano

This improves the performance of the stager query a lot. It changes from:

```sql
UPDATE
  "public"."oban_jobs" AS o0
SET
  "state" = $1
FROM (
  SELECT
    so0."id" AS "id",
    so0."state" AS "state",
    so0."queue" AS "queue",
    so0."worker" AS "worker",
    so0."args" AS "args",
    so0."meta" AS "meta",
    so0."tags" AS "tags",
    so0."errors" AS "errors",
    so0."attempt" AS "attempt",
    so0."attempted_by" AS "attempted_by",
    so0."max_attempts" AS "max_attempts",
    so0."priority" AS "priority",
    so0."attempted_at" AS "attempted_at",
    so0."cancelled_at" AS "cancelled_at",
    so0."completed_at" AS "completed_at",
    so0."discarded_at" AS "discarded_at",
    so0."inserted_at" AS "inserted_at",
    so0."scheduled_at" AS "scheduled_at"
  FROM
    "public"."oban_jobs" AS so0
  WHERE
    (so0."state" IN ($4, $5))
    AND (NOT (so0."queue" IS NULL))
    AND (so0."scheduled_at" <= $2)
  ORDER BY
    so0."id"
  LIMIT
    $3 FOR
  UPDATE
    SKIP LOCKED) AS s1
WHERE
  (o0."id" = s1."id") RETURNING s1."id",
  s1."queue",
  s1."state",
  s1."worker"
```

to

```sql
UPDATE
  "public"."oban_jobs" AS o0
SET
  "state" = $1
FROM (
  SELECT
    so0."id" AS "id"
  FROM
    "public"."oban_jobs" AS so0
  WHERE
    (so0."state" IN ($4, $5))
    AND (NOT (so0."queue" IS NULL))
    AND (so0."scheduled_at" <= $2)
  LIMIT
    $3 FOR
  UPDATE
    SKIP LOCKED) AS s1
WHERE
  (o0."id" = s1."id") RETURNING o0."id",
  o0."queue",
  o0."state",
  o0."worker"
```

The reason is that now it can use the "index only scan" for the compose index in the subquery:

`"oban_jobs_state_queue_priority_scheduled_at_id_index" btree (state, queue, priority, scheduled_at, id)`
 
![image](https://user-images.githubusercontent.com/1745859/218769015-aa53c7c1-082c-4419-83ac-e0e435a8b699.png)

Instead of using "index scan" for the ID index.

The main issue was the "unneeded" order by id.

Our system's average execution time changed from more than 2 seconds to less than 100ms.

2023-02-14 16:37 UTC, sorentwo commented
Hi @alexcastano, thanks for investigating stager performance and working to refine the query. I've attempted to recreate your `index_only_scan` performance locally with 200k scheduled jobs, but there hasn't been a meaningful difference. 

Perhaps the planner makes a more optimized query with a larger volume of jobs?

1. How many scheduled jobs do you have when staging takes 2s?
2. Which version of Postgres are you using?

For reference, here's the [public explain with optimizations](https://explain.depesz.com/s/bH9t) and relevant queries.

2023-02-14 16:52 UTC, sorentwo commented
I managed to get an index-only scan by including a `priority` condition! https://explain.depesz.com/s/Sy69F

2023-02-14 18:17 UTC, alexcastano commented
Hi! I don't understand why PG told me it was using `index only scan`, maybe because I "executed" only the subquery without the outer query. Anyway, I think there is a lot of room for improvement.

The number of "scheduled" jobs is not important for the old query because it was using the id index. It is all the jobs, scheduled or not, you have in the database. We currently have more than 1M rows in the oban_jobs.

Let me apply your suggestion and we'll see the results :)

2023-02-14 19:29 UTC, sorentwo requested changes
I've applied all of my suggestions locally and some test improvements that I'll try to push to this branch.

2023-02-14 19:29 UTC, sorentwo commented on lib/oban/stager.ex
> +      |> select([j, _x], map(j, [:id, :queue, :state, :worker]))
Flipping this returns the wrong `state` information. The purpose of the join/select is to get the original `scheduled` or `retryable` state exposed for telemetry:

```suggestion
      |> select([j, x], %{id: j.id, queue: j.queue, state: x.state, worker: j.worker})
```

2023-02-14 19:29 UTC, sorentwo commented on lib/oban/stager.ex
> +      |> where([j], j.priority >= 0 and j.priority <= 3)
The `>=` and `<=` comparisons won't make use of the index like an `IN` clause:

```suggestion
      |> where([j], j.priority in [0, 1, 2, 3])
```

2023-02-14 19:57 UTC, sorentwo commented
Modified, squashed, and merged locally as 4e2fde8. Thanks again!

2023-02-14 19:57 UTC, closed without merging

2023-02-17 19:38 UTC, alexcastano commented
Hi again!

We deployed the new query in production. It works much faster! However, it doesn't use `index only scan`, but `index scan`. This is the capture from Google Cloud Insights:

![image](https://user-images.githubusercontent.com/1745859/219770700-56108993-4c34-44ce-818a-d2695c97ead0.png)

In addition, when the database is under heavy demand, it sometimes switches back to the slow sequence scan:

![image](https://user-images.githubusercontent.com/1745859/219771427-9dd9ed4e-d9bd-401a-80b4-9ceb3b02d786.png)

I think this behaviour may be expected for postgres, but I wanted to share with you because maybe you can make the query `index only scan`, or maybe ,change the index itself to remove the priority field.

Thanks for your work.

2023-02-20 18:02 UTC, sorentwo commented
That index is used for multiple queries, one of which fetches jobs and requires the priority field. Additionally, changing indexes is an expensive operation we can't do in a transactional migration without blocking.